---

- name: Ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present

- name: Add Elasticsearch apt key.
  apt_key:
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: Add Logstash repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/5.x/apt stable main'
    state: present

- name: Check if Logstash is already installed.
  stat:
    path: /usr/share/logstash
  register: logstash_installed

- name: Update apt cache if repository just added.
  apt: 
    update_cache: yes
  when: logstash_installed.stat.exists == false

- name: Install Logstash.
  apt:
    pkg: logstash
    state: present

- name: Add Logstash user to adm group (Debian).
  user:
    name: logstash
    group: logstash
    groups: adm
  when: ansible_os_family == "Debian"
  notify: restart logstash
